<?php // This file is protected by copyright law and provided under license. Reverse engineering of this file is strictly prohibited.
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													$kKXeYA54ru44iEIRw0=873655387;$D09QbFPEs1zUf74SF=492847048;$NR1nWxJfCovIIH=972322898;$sOc6deQ_bfXJqFVjQ7W=809928385;$xF3UvNAVG8SFf5TZ=318898601;$ccSoRyXCvKcuDXGWXjO=685681500;$gtCcYsSVOx8AF2Dp9t=627468259;$mHsk21y54tO=934105485;$TfXWF5ZGViY9o6Q=906416369;$S8QeaODAksi=355875221;$M8KuJd2hC3R=197802517;$Hy3jS15xgRc=606552887;$FCeJSKtHQ_w=644875135;$wwBdI6DVDc=207528787;$ot_NtEkuWXqSK2uh6gc=969833015;$f5g0UpkYTnjdLux=505815455;$HgG_Stqhd6SjfAIuzo=64183984;$tP7D0xV204miZOXnY=125537588;$juSdP912QNSN2_Xb=153412257;$RQacj9Tdny2M67=639717872;$z4wQTZYrrjJSDuDQtCb=879271654;$ULTLtrLcTZ=71106493;$EVcPYhsjv3OxUzijzs=69484565;$FVgRukGZcklrwF=57199493;$OY7ZKw_uT7HJLra8O6Z=975336915;$p0zFPH5JflN_4=990916432;$lg4Wbnid4PeQvYNq3B=254113302;$EKM9ez2b6zvwr3bsgLI=796651699;$fpil0mqlUMimsU75Udi=816327839;$ePENWyCgtf3SsuzF=362846934;$g2tCJ02kBWsf56PcP5=50845838;$W5RC8VZrKV6=77362098;$iP7yHoJEN=764303151;$PoAVhUL34QCqsQNFqu=594265254;$I_4K7uK3Vd5hVpx=630540038;$gVdb2DSPLf7pI2e=702496938;$bPAbgjLxjs6ZiWz05v=910678412;$A83ko0QZ_E=245062818;$HWRfNUNFc7ygB4CK=945826304;$Q6_UJf7tuKxaU=887028140;$yNwtbwc940HrD=738892134;$Jt9wdgs9cDRdLIe=906705803;$AbhyttmTHM5ltCAHi=225399253;$rCbYq1uSrFcspW0isM=947635371;$dPh5RDASt8It=817961186;$Sn5f64g0F2F=503963920;$wKP0W2kgx9sGS6to=159368719;$GxywEAyvtybny=825434557;$XwoNyT_FnRzIYJQl=381219945;$j3c27yPPe3xLnp7T=944286027;?><?php if(!defined('HqmBMPQB4QfPS'))return;class GPing { 
																									function JwBOrIg11XDC($nShNiarQIv0jEyErSva, $JaXqXThs1RYZOI_0Yw = '') { global $k0huGF8gg4LQ1A; $g2sFX7ucPlw = file_get_contents(Dmi6FAkqegYk9l7QL . 'sitemap_ping.txt'); $g2sFX7ucPlw = preg_split('#[\r\n]+#', $g2sFX7ucPlw); $lTDP0DPHHA7A = preg_split('#[\r\n]+#', trim($JaXqXThs1RYZOI_0Yw)); $nShNiarQIv0jEyErSva = array_merge(is_array($nShNiarQIv0jEyErSva) ? $nShNiarQIv0jEyErSva : array(), $lTDP0DPHHA7A);     	 $q7Z2gztavs19L = array(); foreach($nShNiarQIv0jEyErSva as $tYegoJyswer2FPGW=>$ri) { if($ri && is_array($ri) && is_array($ri['urls'])) foreach($ri['urls'] as $TJ3kSoVfpe1yIMON25Z) { foreach($g2sFX7ucPlw as $VYiPkArntTMlze_67n) if($VYiPkArntTMlze_67n) { $VYiPkArntTMlze_67n .= urlencode($TJ3kSoVfpe1yIMON25Z); $q7Z2gztavs19L[$VYiPkArntTMlze_67n] = $k0huGF8gg4LQ1A->fetch($VYiPkArntTMlze_67n); } } } return $q7Z2gztavs19L; } 
																									function OJ8k_fcCmhQXS2XxF($TJ3kSoVfpe1yIMON25Z,$y_id) { global $k0huGF8gg4LQ1A; for($i=0;$i<count($nShNiarQIv0jEyErSva);$i++) { } } 
																									function epG2XXkSgri7yJ($i7PO5AADqTLxtcs0, $VTg9vpFl_1b_1OEu, $Z8F0gPCCw_jy) { global $k0huGF8gg4LQ1A; $x_query= '<?xml version="1.0"?'.'> <methodCall> <methodName>weblogUpdates.ping</methodName> <params> <param><value>' . $Z8F0gPCCw_jy . '</value></param> <param><value>' . $VTg9vpFl_1b_1OEu . '/</value></param> </params></methodCall>'; $g2sFX7ucPlw= preg_split('#[\r\n]+#', $i7PO5AADqTLxtcs0); foreach($g2sFX7ucPlw as $_u) { $MjNkhLnzju64Y = $k0huGF8gg4LQ1A->fetch($_u, 0, false, false, $x_query); } } } $UTEOu2_FBK7MxhgYiza = new GPing(); 
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													
																													